name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Bevy Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev libudev-dev

    - name: Build target wasm32-unknown-unknown
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target wasm32-unknown-unknown

    - name: Install wasm-bindgen-cli
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: wasm-bindgen-cli

    - name: Run wasm-bindgen 
      run: wasm-bindgen --out-dir ./target/web --target web ./target/wasm32-unknown-unknown/debug/super_duper_octo_spoon_bg.wasm

    - name: Package static files
      run: |
        cp index.html ./target/web
        cp -r assets ./target/web
        tar -czvf target/web.tar.gz -C target/web .

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.0
      with:
        path: ./target/web.tar.gz
  
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.3  
